[colors.primary]
background = "#0D0908"
foreground = "#F7F3F2"

[cursor]
style = "Beam"

[font]
size = 12

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[window]
decorations = "Full"

[window.padding]
x = 12
y = 8
